name: telegram message
on: 
  pull_request:
    types: [opened, reopened]
   
  issues:
    types: [opened, reopened]
   
  issue_comment:
    types: [created]
   
  pull_request_review_comment:
    types: [create]
  
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: The ${{ github.pull_request }} event triggered first step.
